version: "3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - redisdata:/data

  postgres:
    container_name: postgres
    image: postgres:11.5
    ports:
    - "5431:5432"
    volumes:
    - postgresdata:/data/postgres
    - postgresdbdata:/var/lib/postgresql/data
    env_file:
    - docker.env
    networks:
    - postgres

  elastic:
    container_name: elastic
    image: elasticsearch:7.4.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - elasticsearchdata:/data/elastic
    env_file:
    - docker.env
    ports:
    - 9200:9200
    networks:
    - elastic
    environment:
    - discovery.type=single-node

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "9090:80"
    volumes:
    - pgadmindata:/root/.pgadmin
    - pgadminlibdata:/var/lib/pgadmin
    env_file:
    - docker.env
    networks:
    - postgres

volumes:
  redisdata:
    driver: local
  postgresdata:
    driver: local
  postgresdbdata:
    driver: local
  pgadmindata:
    driver: local
  pgadminlibdata:
    driver: local
  elasticsearchdata:
    driver: local


networks:
  postgres:
    driver: bridge
  elastic:
    driver: bridge